version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo@123
      POSTGRES_DB: demo_db
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    # image: test_img
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
        - db
